include $(TOPDIR)/rules.mk

PKG_NAME:=luci-app-bandpush
PKG_VERSION:=1.0.0
PKG_RELEASE:=1

LUCI_TITLE:=BandPush
LUCI_DEPENDS:=+luci-compat +curl +lua
LUCI_PKGARCH:=all

include $(TOPDIR)/feeds/luci/luci.mk